<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-7IO1P8C" failures="1" tests="1" name="Test" time="1.516" errors="0" timestamp="2023-10-01T02:28:20 IST">
  <testcase classname="Test_NG_FrameWork_2.Data_Provider_Login_Provider_2" name="mainCodes" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.io.FileNotFoundException: C:\Users\Admin\Desktop\DataProvider.xlsx (The process cannot access the file because it is being used by another process)">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: C:\Users\Admin\Desktop\DataProvider.xlsx (The process cannot access the file because it is being used by another process)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.io.FileNotFoundException: C:\Users\Admin\Desktop\DataProvider.xlsx (The process cannot access the file because it is being used by another process)
at java.base/java.io.FileOutputStream.open0(Native Method)
at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:236)
at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:185)
at org.apache.poi.openxml4j.opc.internal.FileHelper.copyFile(FileHelper.java:65)
at org.apache.poi.openxml4j.opc.ZipPackage.closeImpl(ZipPackage.java:480)
at org.apache.poi.openxml4j.opc.OPCPackage.close(OPCPackage.java:470)
at org.apache.poi.ooxml.POIXMLDocument.close(POIXMLDocument.java:189)
at org.apache.poi.xssf.usermodel.XSSFWorkbook.close(XSSFWorkbook.java:610)
at Test_NG_FrameWork_2.Data_Provider_Login_Provider_2.setDataa(Data_Provider_Login_Provider_2.java:91)
... 25 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- mainCodes -->
</testsuite> <!-- Test -->
